### ISSUE TITLE
All models should be in `models.py`

### ISSUE THREAD

**Issue by cmutel** [lilliputten/dds-invoicing-app#22]

**Comment by cmutel** [comment]
This means that the `Application` class should be moved.

Similarly, the forms in `ApplicationForm` should be in `forms.py`.

**Comment by lilliputten** [comment]
I don't usually like to have huge piles of code in one place, but that's ok, if we need it.

**Comment by cmutel** [comment]
> I don't usually like to have huge piles of code in one place, but that's ok, if we need it.

`models` can also be a subdirectory

**Comment by lilliputten** [comment]
> > I don't usually like to have huge piles of code in one place, but that's ok, if we need it.
> 
> `models` can also be a subdirectory

Yep, mb, that's a solution. I didn't know that. Perhaps, will try it later.
